    services:
        directus:
            image: directus/directus:11.5.1
            ports:
                - 8055:8055
            volumes:
                - ./database:/directus/database
                - ./uploads:/directus/uploads
                - ./extensions:/directus/extensions
            environment:
                SECRET: "replace-with-random-value"
                ADMIN_EMAIL: "admin@example.com"
                ADMIN_PASSWORD: "d1r3ctu5"
                DB_CLIENT: "sqlite3"
                DB_FILENAME: "/directus/database/data.db"
                WEBSOCKETS_ENABLED: "true"
                CORS_ENABLED: true
                CORS_ORIGIN: "http://localhost:5173"
                CORS_METHODS: "GET,POST,PATCH,DELETE,OPTIONS"
                CORS_ALLOWED_HEADERS: "Content-Type,Authorization,X-Requested-With,Origin,Accept"
                CORS_EXPOSED_HEADERS: "Content-Range,X-Total-Count"
                CORS_CREDENTIALS: "true"
                CORS_MAX_AGE: 18000
                